yanet-platform/yanet2

sock-send/meson.build
Ubuntu 22.04, for example, does not provide libpcap static libraries for licensing reasons, I suppose. So let's link dynamically instead.
=> fix: link with libpcap dynamically for sock-send

dataplane/dataplane.c, dataplane/device.h, dataplane/dpdk.c, dataplane/dpdk.h, dataplane/modules/balancer.c, dataplane/modules/kernel.c, dataplane/modules/route.c, dataplane/packet/encap.c, dataplane/packet/packet.c, dataplane/packet/packet.h
This commit makes our codebase's API (which are header files) isolated from DPDK by removing DPDK includes in header files. Ideally we also must hide rte_* symbols in translation units. This potentially gives us independence from DPDK version, but this change is not going to be implemented right now.
Segregating header files from DPDK includes is also a prerequesite for DPDK-less build for lightweighted checks in github.
=> refactor: no DPDK includes in header files

common/container_of.h, common/data_pipe.h, common/key.h, common/lpm.h, common/network.h, common/radix.h, common/range_collector.h, common/registry.h, common/remap.h, common/value.h, dataplane/dataplane.h, dataplane/device.h, dataplane/dpdk.h, dataplane/drivers/sock_dev.h, dataplane/module.h, dataplane/modules/acl.h, dataplane/modules/balancer.h, dataplane/modules/decap.h, dataplane/modules/kernel.h, dataplane/modules/route.h, dataplane/packet/encap.h, dataplane/packet/packet.h, dataplane/pipeline.h, dataplane/worker.h, filter/classify.h, filter/ipfw.h
Instead of coming up with names of header guards I suggest to use #pragma once directive. It's hard to find compilers that do not support this.
Pros:
- No need to figure out how to name header guards.
- No more chance of clashing, since current guards are not generic enough.
Cons:
- Don't see anything. Maybe we lose a chance to be compiled on ancient compilers.
Closes #6.
=> refactor: use pragma once instead of header guards

lib/dataplane/module/testing.c, lib/dataplane/module/testing.h, tests/go/common/packet.go, tests/go/modules/decap/decap.go
This PR addresses memory management within our tests by eliminating unhandled allocations on the C heap. All memory management is now consolidated within the Go heap, reducing potential memory management issues.
=> fix: zero-copy interaction with CGO in tests

dataplane/unittest/main.c, modules/route/controlplane.c, modules/route/controlplane.h
The value type should be `uint32_t` to be consistent with the LPM value type and other functions in the "route" module.
=> fix: proper type for route indices

controlplane/modules/route/internal/rib/map_trie.go, controlplane/modules/route/internal/rib/map_trie_test.go, controlplane/modules/route/internal/rib/rib.go, controlplane/modules/route/service.go
The most noticable change - MapTrie is now a generic structure, where the type parameter V represents the value type stored for each prefix.
Performance changes:
- InsertOrUpdate method now accepts two functions. The first one is called on empty value. The second is called when a value exists and needs to be updated. This results in less unnecessary allocations.
Minor changes:
- Add traversal functions to MapTrie.
- Add documentation for previously undocumented functions in MapTrie.
- Rewrite tests to improve readability and cause and effect relationship.
=> refactor: make MapTrie generic

controlplane/etc/yanet/controlplane-director.yaml, controlplane/internal/gateway/cfg.go, controlplane/internal/gateway/gateway.go, controlplane/internal/gateway/proxy.go, web/.rustfmt.toml, web/Cargo.lock, web/Cargo.toml, web/build.rs, web/src/api/mod.rs, web/src/api/neighbour.rs, web/src/components/demo.rs, web/src/lib.rs
The idea is to terminate HTTP requests on Gateway side, then just pass them directly to gRPC streams without modification.
This approach allows to forward requests/responses without knowing its protobuf definition, and that's the reason why we don't use go-grpc-gateway to solve the issue.
=> feat: HTTP <-> gRPC transparent proxy

common/lpm.h, common/memory.h, modules/route/controlplane.c, tests/common/lpm_test.c, tests/common/meson.build, tests/meson.build
The size of pages region to be freed was evaluated incorrectly.
Also check `lpm_init` status for route module initialization
=> Fix inconsistent memory freeing while error handling

agent/info/main.go, api/agent.h, common/strutils.h, lib/controlplane/agent/agent.c, lib/controlplane/agent/agent.h
The commit adds routines to fetch and decode information about agents connected to `YANET` shared memory. At the point one may list all connected agents with history and fetch information about `pid` and memory consumption of each connection instance in form like
```
Agent bootstrap
Pid 12579 Limit 4194304 Allocated 336 Freed 0
Pid 12572 Limit 4194304 Allocated 336 Freed 0
Pid 12565 Limit 4194304 Allocated 336 Freed 0
Pid 12559 Limit 4194304 Allocated 336 Freed 0
Pid 5479 Limit 4194304 Allocated 336 Freed 0
```
=> Agent introspection

.gitignore, cli/Cargo.lock, cli/modules/neighbour/Cargo.toml, cli/modules/neighbour/src/lib.rs, cli/modules/neighbour/src/main.rs, common/rust/netip/.rustfmt.toml, common/rust/netip/Cargo.toml, common/rust/netip/src/lib.rs, controlplane/Makefile, controlplane/modules/route/neighbour_service.go, controlplane/modules/route/routepb/macaddr.go, controlplane/modules/route/routepb/macaddr.proto, controlplane/modules/route/routepb/neighbour.proto, web/Cargo.lock, web/Cargo.toml, web/src/components/demo.rs, web/src/components/neighbour.rs
This commit changes the way we pass MAC addresses in protobuf. Instead of strings we now pass them as a separate struct containing a single 64-bit field, which encodes a MAC address in big-endian.
This ensures that MAC addresses are correct, and no from-strings-parsing in CLI and web components is now required. Previously we had to check for errors while doing so.
Now we won't.
=> refactor: use MAC address type instead of strings in protobuf

controlplane/Makefile, controlplane/modules/forward/cfg.go, controlplane/modules/forward/ffi.go, controlplane/modules/forward/forwardpb/forward.proto, controlplane/modules/forward/mod.go, controlplane/modules/forward/service.go, controlplane/yncp/cfg.go, controlplane/yncp/director.go, modules/forward/controlplane.c
This PR implements the `forward` module in the controlplane, providing a GRPC API to configure dataplane forwarding. The implementation follows the same pattern as existing modules (e.g., `decap` and `route`), but is tailored for L2/L3 forwarding operations.
- Implemented `forward` module with proper FFI integration for dataplane communication
- Added GRPC service for configuring device and network forwarding rules
- Added comprehensive validation and error handling
- Ensured proper configuration persistence across NUMA nodes
- Fixed edge cases for device removal and forward rule management
- Add/remove L2 forwarding devices
- Configure IPv4 and IPv6 network forwarding rules
- Per-NUMA node configuration
- Proper resource cleanup when removing devices (removes orphaned forwards)
- Used …
=> feat: add the controlplane for the forwrad module

modules/nat64/api/nat64cp.c, modules/nat64/cli/src/main.rs, modules/nat64/controlplane/nat64pb/nat64.proto, modules/nat64/controlplane/service.go, modules/nat64/dataplane/config.h, modules/nat64/dataplane/nat64dp.c
This PR implements a more robust approach to handling IPv6 extension headers in NAT64 module, fixing issues found by fuzzing.
- Remove `options_limit` configuration option in favor of strict RFC 8200 compliance
- Add proper validation of IPv6 extension headers:
- Enforce Hop-by-Hop Options header to be first if present (RFC 8200 Section 4.1)
- Limit maximum number of extension headers to 8
- Prevent duplicate headers (except Destination Options which can appear twice)
- Add bounds checking for extension header processing
- Track seen headers using bitmap for efficient validation
- Clean up related code in control plane and CLI
The changes have been verified by fuzzing tests that previously detected the issue.
- RFC 8200 Section 4: IPv6 Extension Headers
- RFC 7915: Translation between …
=> Another way to fix the bug found by fuzz.

api/agent.h, lib/controlplane/agent/agent.c
The commit introduces few API functions for retrieving configured devices with pipelines assigned to.
Closes #141
=> `Controlplane` device introspection

coordinator/etc/yanet/yanet-coordinator.yaml, coordinator/internal/stage/cfg.go, coordinator/internal/stage/stage.go
This PR fixes the pipeline assignment logic in the coordinator by updating the configuration to handle multiple pipelines per NUMA node and assigning them to devices.
- Updated the stage setup to iterate over multiple pipelines instead of a single pipeline.
- Introduced a new function to assign pipelines to devices.
- Modified configuration files and YAML examples to reflect multiple pipelines and device assignments.
=> fix: properly assign pipelines in coordinator

modules/route/controlplane/internal/rib/rib.go
This PR fixes a missing functionality by adding the required fields to static routes in the RIB. The key changes include:
- Setting the SourceID to RouteSourceStatic on insert unicast static
route.
- Initializing the UpdatedAt field with the current time.
=> fix: add missing fields for static routes

modules/route/controlplane/internal/discovery/cache.go, modules/route/controlplane/internal/discovery/neigh/neigh.go, modules/route/controlplane/neighbour_service.go
This PR aims to fix the age correction for neighbour entries by adjusting how neighbour entries are retrieved and updated within the controlplane modules.
- Updated retrieval of neighbour entries from the cache using an iterator and a size for capacity allocation.
- Updated neighbour monitor to compare and assign the UpdatedAt field from the cache view.
- Refactored the cache view to return an iterator along with the size to avoid making a full copy.
=> fix: correct age for neighbour entries

modules/nat64/cli/src/main.rs
This PR fixes a compilation issue in the NAT64 CLI by adjusting imports and function closures.
- Moves the import of ipnet::Ipv6Net to a new position
- Adds a closing brace in the set_mtu function to properly terminate its block
=> fix: nat64 CLI compilation

common/go/bitset/bitset.go, common/go/bitset/bitset_test.go, controlplane/ffi/shm.go, controlplane/internal/gateway/inspect_service.go, modules/route/controlplane/ffi.go
This PR refactors the iterable bitset implementation by changing the output type from int to uint32, ensuring consistent type usage across API functions and tests.
- Update RouteListAdd to accept []uint32 in the FFI interface.
- Modify Traverse callbacks and iteration methods to use uint32 with a bool return value for early termination support.
- Update tests to reflect these type changes in bitset behavior.
=> refactor: iterable bitset, change output type to uint32

dataplane/meson.build, lib/controlplane/agent/meson.build, lib/controlplane/config/meson.build, lib/dataplane/packet/meson.build, lib/meson.build, meson.build, modules/acl/meson.build, modules/balancer/meson.build, modules/decap/api/meson.build, modules/decap/dataplane/decap_dp.map, modules/decap/dataplane/meson.build, modules/decap/meson.build, modules/dscp/api/meson.build, modules/dscp/dataplane/meson.build, modules/dscp/meson.build, modules/forward/api/meson.build, modules/forward/dataplane/meson.build, modules/forward/meson.build, modules/nat64/api/meson.build, modules/nat64/dataplane/meson.build, modules/nat64/meson.build, modules/nat64/tests/dataplane/meson.build, modules/route/api/meson.build, modules/route/dataplane/meson.build, modules/route/meson.build
**Standardize module dependencies, optimize build targets, and improve build performance**
This PR addresses a pattern of implicit dependency management across several DPDK modules. Previously, modules often relied on `dependencies = []` or `+=` to manage their dependencies, which can lead to ambiguity and potential conflicts during builds.
This change introduces explicit dependency lists for several modules, ensuring that all required libraries are clearly defined. Specifically, `lib_common_dep` and `lib_logging_dep` are now explicitly included in the dependency lists for `route` and `nat64` modules.
**Motivation:**
*   **Improved Build Performance:** A significant optimization was achieved by changing the configuration from `disable_drivers` to `enable_drivers`. This change drastically …
=> fix: improve build speed and cleanup

Cargo.lock, cli/modules/inspect/src/main.rs, common/rust/bitmap/Cargo.toml, common/rust/bitmap/src/lib.rs, controlplane/internal/gateway/inspect_service.go, controlplane/ynpb/inspect.proto, modules/decap/cli/Cargo.toml, modules/decap/cli/build.rs, modules/decap/cli/src/main.rs, modules/decap/controlplane/decappb/decap.proto, modules/decap/controlplane/service.go
This commit refactors the target configuration by renaming "module_name" to "config_name" and revising NUMA index handling in the decap module, updating both service and CLI implementations.
- Refactored validation by replacing getNUMAIndices with validateTarget to return a single NUMA index instead of a list.
- Updated protobuf definitions and adjusted CLI arguments and build scripts accordingly.
Stage: [2/5]
=> refactor: module_name -> config_name for decap

modules/pdump/controlplane/ring.go, modules/pdump/controlplane/service.go
Enhances the packet dump module to support multiple concurrent readers and implements safe configuration updates to prevent memory access violations.
**Multiple Reader Support:**
- Added `Clone()` method to [`ringBuffer`](modules/pdump/controlplane/ring.go:53) for creating independent reader instances
- Each reader gets its own copy of worker areas to avoid concurrent modification issues
- Enables multiple concurrent `ReadDump` streams for the same capture instance
**Safe Configuration Updates:**
- Implemented proper termination of active ring readers before config changes
- Added [`ringReader`](modules/pdump/controlplane/service.go:47) tracking with cancellation support
- Prevents segmentation faults by ensuring readers are stopped before shared memory deallocation
**Enhanced Service …
=> feat(pdump): support multiple readers, safe config update

dataplane/config.c
Free dataplane config instance on realloc failure during config parsing.
=> dataplane-config: handle realloc error on parsing.

docs/virtual-run.org, modules/forward/api/controlplane.c, modules/forward/api/controlplane.h, modules/forward/cli/build.rs, modules/forward/cli/src/main.rs, modules/forward/controlplane/ffi.go, modules/forward/controlplane/forwardpb/forward.proto, modules/forward/controlplane/forwardpb/meson.build, modules/forward/controlplane/service.go, modules/forward/controlplane/service_test.go, modules/forward/coordinator/service.go
This PR refactors the forward module to use a unified `commonpb.TargetModule` instead of module-specific targeting, improving consistency across the yanet2 codebase.
**API Standardization:**
- Replace `forwardpb.TargetModule` with `commonpb.TargetModule` across all forward module components
- Change from bitmask-based instance targeting (`Instances: 0b1`) to single instance targeting (`DataplaneInstance: 0`)
- Rename `ModuleName` field to `ConfigName` for clarity
**CLI Updates:**
- Update yanet-cli commands to use `--cfg` and `--instance` flags instead of `--mod`
- Standardize command syntax across forward, decap, route, and dscp modules
- Update documentation examples in `virtual-run.org` with new CLI syntax
**Service Layer Changes:**
- Refactor controlplane service to handle …
=> refactor(forward): iterate through instances on the CLI side

common/network.h, filter/attribute.h, filter/attribute/net4.h, filter/attribute/net6.h, filter/attribute/util.h, filter/filter.h, filter/ipfw.c, filter/rule.h, filter/tests/basic_net6.c, filter/tests/meson.build, filter/utils/utils.c, filter/utils/utils.h
This PR brings support for non-consecutive IPv6 masks in filter.
For now, only masks of the following type are supported: _AB_, where _A_ and _B_ are prefix-consecutive masks of length 64.
This PR refers to issues [232](https://github.com/yanet-platform/yanet2/issues/232) and [233](https://github.com/yanet-platform/yanet2/issues/233).
=> NCM IPv6 support in filter
